namespace BuildNugetDependencyTree;

public class DependencyTreeDisplay
{
    public void DisplayPackageProducers(DependencyTree tree, List<ProjectInfo> projects)
    {
        Console.WriteLine("\n=== PROJECTS THAT GENERATE NUGET PACKAGES ===\n");
        foreach (var rootNode in tree.PackageNodes)
        {
            var projectInfo = projects.First(p => p.FilePath == rootNode.ProjectFilePath);
            string source = !string.IsNullOrEmpty(projectInfo.NuspecFilePath)
                ? $"(via .nuspec: {Path.GetFileName(projectInfo.NuspecFilePath)})"
                : "(via .csproj)";

            Console.WriteLine($"📦 {rootNode.PackageId} {source}");
            Console.WriteLine($"   Project: {Path.GetFileName(rootNode.ProjectFilePath)}");
            Console.WriteLine($"   Path: {rootNode.ProjectFilePath}");
            Console.WriteLine();
        }
    }

    public void DisplayDependencyTree(DependencyTree tree)
    {
        Console.WriteLine("\n=== NUGET PACKAGE DEPENDENCY TREE ===\n");
        foreach (var rootNode in tree.PackageNodes.Where(n => n.Consumers.Any()))
        {
            PrintTreeNode(rootNode, 0);
            Console.WriteLine();
        }
    }

    public void DisplaySummary(DependencyTree tree, int relationshipCount)
    {
        Console.WriteLine("\n=== SUMMARY ===");
        Console.WriteLine($"Total projects scanned: {tree.TotalProjects}");
        Console.WriteLine($"Projects generating NuGet packages: {tree.PackageNodes.Count}");
        Console.WriteLine($"Projects with package references: {tree.ProjectsWithDependencies}");
        Console.WriteLine($"Total dependency relationships: {relationshipCount}");
    }

    private void PrintTreeNode(PackageNode node, int indent)
    {
        string indentStr = new string(' ', indent * 3);
        Console.WriteLine($"{indentStr}📦 {node.PackageId}");
        Console.WriteLine($"{indentStr}   └─ Generated by: {node.ProjectName}");

        foreach (var consumer in node.Consumers)
        {
            PrintConsumerNode(consumer, indent + 2);
        }
    }

    private void PrintConsumerNode(ConsumerNode node, int indent)
    {
        string indentStr = new string(' ', indent * 3);
        string label = node.GeneratesPackage
            ? $"{node.ProjectName} → Generates: {node.GeneratedPackageId}"
            : node.ProjectName;

        Console.WriteLine($"{indentStr}└─ Consumed by: {label}");

        foreach (var transitive in node.TransitiveConsumers)
        {
            PrintTransitiveNode(transitive, indent + 1);
        }
    }

    private void PrintTransitiveNode(ConsumerNode node, int indent)
    {
        string indentStr = new string(' ', indent * 3);
        string label = node.GeneratesPackage
            ? $"{node.ProjectName} → Generates: {node.GeneratedPackageId}"
            : node.ProjectName;

        Console.WriteLine($"{indentStr}└─ Transitively consumed by: {label}");

        foreach (var transitive in node.TransitiveConsumers)
        {
            PrintTransitiveNode(transitive, indent + 1);
        }
    }
}
