using System.Diagnostics;

namespace DoenaSoft.BuildNugetDependencyTree.Models;

/// <summary>
/// Represents a project that consumes a package, including its transitive consumers.
/// </summary>
[DebuggerDisplay("{ProjectName,nq} | Generates: {GeneratedPackageId,nq} | Transitive: {TransitiveConsumers.Count}")]
public class ConsumerNode
{
    /// <summary>
    /// Gets or sets the file path to the consumer project.
    /// </summary>
    public string ProjectFilePath { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the name of the consumer project.
    /// </summary>
    public string ProjectName { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets whether this consumer project generates a NuGet package.
    /// </summary>
    public bool GeneratesPackage { get; set; }

    /// <summary>
    /// Gets or sets the package ID generated by this consumer project, if any.
    /// </summary>
    public string? GeneratedPackageId { get; set; }

    /// <summary>
    /// Gets or sets the list of projects that transitively consume through this consumer.
    /// </summary>
    public List<ConsumerNode> TransitiveConsumers { get; set; } = [];
}
