using System.Diagnostics;

namespace DoenaSoft.BuildNugetDependencyTree.Models;

/// <summary>
/// Represents information about a .NET project, including its package generation settings and dependencies.
/// </summary>
[DebuggerDisplay("{ProjectName,nq} | PackageId: {PackageId,nq} | Refs: {PackageReferences.Count}")]
public class ProjectInfo
{
    /// <summary>
    /// Gets or sets the file path to the .csproj file.
    /// </summary>
    public string FilePath { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the NuGet package ID generated by this project, if any.
    /// </summary>
    public string? PackageId { get; set; }

    /// <summary>
    /// Gets or sets the version of the NuGet package generated by this project.
    /// </summary>
    public string? PackageVersion { get; set; }

    /// <summary>
    /// Gets or sets the file path to the .nuspec file, if one is used.
    /// </summary>
    public string? NuspecFilePath { get; set; }

    /// <summary>
    /// Gets or sets the list of NuGet packages referenced by this project.
    /// </summary>
    public List<PackageReference> PackageReferences { get; set; } = [];

    private string ProjectName => Path.GetFileNameWithoutExtension(this.FilePath);
}
